# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: NewLandlordHQ
email: john@newlandlordhq.com
description: > # this means to ignore newlines until "baseurl:"
  Your single resource for becoming a successful landlord.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.newlandlordhq.com" # the base hostname & protocol for your site
twitter_username: newlandlordhq
github_username:  nlhq

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /:year/:month/:day/:title

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "John"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
